name: Build and Deploy
on:
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        check-latest: true
    - name: Build
      run: yarn && yarn docs:build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vuepress/dist/
        force_orphan: true
